kind: Rules
metadata:
  namespace: k8s-tutorial
spec:
  - name: "k8s.StandardJavaSvcProd"
    description: "Standard configuration for Java FE application in K8s PROD"
    condition:
      deployedType: k8s.Resources
      expression: "#input.getStringValue('$.kind') == 'Deployment'"
      expression: "#ctx.deployedApplication.environment.name == 'kubernetes-env-prod'"      
    processor:
      - type: patch
        description: "Changing replicas to 3 and setting resource limits"
        phase: POST_FLIGHT
        merge:
          type: overlay
        parameters:
          patch:
            - op: replace
              path: "/spec/replicas"
              value: 3
            - op: replace
              path: "/spec/template/spec/containers/0/resources/limits/cpu"
              value: 2
            - op: replace
              path: "/spec/template/spec/containers/0/resources/limits/memory"
              value: "4096Mi"