kind: Rules
metadata:
  namespace: k8s-tutorial
spec:
  - name: "k8s.ChangePortForService"
    description: "Enforces use of port 8081 instead of 8080 for a K8s service"
    condition:
      deployedType: k8s.Resources
      expression: "#input.getStringValue('$.kind') == 'Service'" # activate only for kind:Service
      expression: "#input.getIntegerValue('$.spec.ports[0].port') == 8080" # activate only is Service port is 8080
    processor:
      - type: patch
        description: "Changing port for service"
        phase: PATCH
        merge:
          type: overlay
        parameters:
          patch:
            - op: replace
              path: "/spec/ports/0/port"
              value: 8081
